import type { Metadata } from "next";
import "./globals.css";
import Navabar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { Sora } from "next/font/google";
import { Montserrat } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});
export const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col bg-(--bg) ${sora.className}`}
        suppressHydrationWarning={true}
      >
        <Navabar></Navabar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
