import type { Metadata } from "next";
import "./globals.css";
import Navabar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { sora } from "@/lib/fonts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col bg-(--bg) ${sora.className}`}
        suppressHydrationWarning={true}
      >
        <Navabar></Navabar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
