import type { Metadata } from "next";
import "./globals.css";
import Navabar from "@/components/layout/Navbar";
import { Sora } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-full flex flex-col bg-(--bg) ${sora.className}`} suppressHydrationWarning={true}>
        <Navabar></Navabar>
        {children}
      </body>
    </html>
  );
}
